#!/bin/bash

set -e

usage() { echo "Usage: $0 -f [stack-file.yml] compile|deploy" 1>&2; exit 1; }


# parse cmdline
while getopts ":f:" o; do
    case "${o}" in
        f)
          infile=${OPTARG}
            ;;
        *)
            usage
            ;;
    esac
done

shift $((OPTIND-1))

# validate args
[ ! -f $infile ] && usage
action=$1   # deploy or compile


# start things
echo "Processing stack in '$infile'"

stack_ns=$(yq -e e '.ns' $infile 2>/dev/null) || stack_ns="${infile%.*}"

echo "Working with stack '$stack_ns' from $(yq e '.files | .[] | select(.)' $infile| wc -l) files"
for compose_file in $(yq e '.files | .[] | select(.)' $infile); do
  stack="${stack}$(cat $compose_file)\n---\n"
done;

current_stack=.docker-stack-${stack_ns}.yml



compiled=$(echo -e "$stack" | yq -j ea '
    sortKeys(..) |
    del(.x-*)' - |
    yq -P eval-all '. as $item ireduce ({}; . * $item ) |
    sortKeys(.services) | sortKeys(.config) | sortKeys(.volumes) |
    {"version":.version, "configs":.configs, "networks":.networks, "volumes":.volumes, "services":.services}
  ' - )


if [[ $action == "deploy" ]] ; then

  [ -f "$current_stack" ] && diff -q "$current_stack" <(echo -e "$compiled") || (echo "Change detected, please compile first" && exit 1)

  docker stack deploy
    --with-registry-auth \
    --compose-file "$current_stack" \
    web-monitor

  docker service ls
fi

if [[ $action == "compile" ]] ; then
  in=$current_stack
  [ ! -f "$in" ] && in=/dev/null
  diff -q "$in" <(echo -e "$compiled") && echo "No changes detected" || ( diff -y <(echo -e "current stack\n---"; cat "$in")  <(echo -e "next stack\n---"; echo -e "$compiled") | colordiff | most)

  read -p "Confirm [y/N]: " commit
  commit=$(echo -n ${commit:-n} | tr '[:upper:]' '[:lower:]')

  [ $commit != "y" ] && exit 1;

  echo -e "$compiled" > $current_stack
  echo "Stack wrote in $current_stack"
fi



if [[ $action == "validate" ]] ; then
  echo -e "$compiled" | yq -P e '' -
  exit 0;
fi




