name: tests
on:
  - push
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - run: docker node ls -q || docker swarm init
      - run: npm install
      - run: npm test
        env:
          DEBUG: "*,-babel,-eslint:*,-eslintrc:*,-mocha:*"
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
